server:
  port: 8071


spring:
  application:
    name: user-api

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8761/eureka/
